# <center> Préparation des données de train et de test </center>

## Première étape: Importation des librairies nécessaires

In [1]:
from bigml.api import BigML
from pandas import read_csv

*<center>Préciser l'id du projet BigML</center>*

In [2]:
api = BigML(project= 'project/5d94a407eba31d45c8000088')

## Deuxième Etape: Importer les données de train

*<center> Rajout de features aux données trainfull </center>*

In [3]:
df = read_csv('../handson-ml2/kaggle-give-me-credit-train.csv')

In [4]:
df = df.fillna(0)
df['IncomePerPerson'] = df['MonthlyIncome']/ (df['NumberOfDependents']+1)
df['NumberOfDaysLate'] = df['NumberOfTimes90DaysLate']+ df['NumberOfTime60-89DaysPastDueNotWorse']+ df['NumberOfTime30-59DaysPastDueNotWorse']
df['NumberCreditLines'] = df['NumberOfOpenCreditLinesAndLoans']- df['NumberRealEstateLoansOrLines']
df['MonthlyDebt'] = df['MonthlyIncome'] * df['DebtRatio']
df['MonthlyBalance'] = df['MonthlyIncome'] - df['MonthlyDebt']
df['DebtPerPerson'] = df['MonthlyDebt'] / ( df['NumberOfDependents'] + 1 )
df = df.rename(columns={"Unnamed: 0": "Id"})
df

,Id,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,SeriousDlqin2yrs,IncomePerPerson,NumberOfDaysLate,NumberCreditLines,MonthlyDebt,MonthlyBalance,DebtPerPerson
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,1,3040.000000,2,7,7323.197016,1796.802984,2441.065672
1,2,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,0,1300.000000,0,4,316.878123,2283.121877,158.439061
2,3,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,0,3042.000000,2,2,258.914887,2783.085113,258.914887
3,4,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,0,3300.000000,0,5,118.963951,3181.036049,118.963951
4,5,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,0,63588.000000,1,6,1584.975094,62003.024906,1584.975094
5,6,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0,0,1750.000000,0,2,1314.624392,2185.375608,657.312196
6,7,0.305682,57,0,5710.000000,0.0,8,0,3,0,0.0,0,0.000000,0,5,0.000000,0.000000,0.000000
7,8,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0,0,3500.000000,0,8,734.790059,2765.209940,734.790059
8,9,0.116951,27,0,46.000000,0.0,2,0,0,0,0.0,0,0.000000,0,2,0.000000,0.000000,0.000000
9,10,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0,0,7894.666667,0,5,14359.393699,9324.606301,4786.464566
10,11,0.644226,30,0,0.309476,2500.0,5,0,0,0,0.0,0,2500.000000,0,5,773.690525,1726.309475,773.690525
11,12,0.018798,51,0,0.531529,6501.0,7,0,2,0,2.0,0,2167.000000,0,5,3455.468469,3045.531531,1151.822823
12,13,0.010352,46,0,0.298354,12454.0,13,0,2,0,2.0,0,4151.333333,0,11,3715.701650,8738.298350,1238.567217
13,14,0.964673,40,3,0.382965,13700.0,9,3,1,1,2.0,1,4566.666667,7,8,5246.617034,8453.382966,1748.872345
14,15,0.019657,76,0,477.000000,0.0,6,0,1,0,0.0,0,0.000000,0,5,0.000000,0.000000,0.000000
15,16,0.548458,64,0,0.209892,11362.0,7,0,1,0,2.0,0,3787.333333,0,6,2384.790109,8977.209891,794.930036
16,17,0.061086,78,0,2058.000000,0.0,10,0,2,0,0.0,0,0.000000,0,8,0.000000,0.000000,0.000000
17,18,0.166284,53,0,0.188274,8800.0,7,0,0,0,0.0,0,8800.000000,0,7,1656.811728,7143.188272,1656.811728
18,19,0.221813,43,0,0.527888,3280.0,7,0,1,0,2.0,0,1093.333333,0,6,1731.472112,1548.527888,577.157371
19,20,0.602794,25,0,0.065868,333.0,2,0,0,0,0.0,0,333.000000,0,2,21.934132,311.065868,21.934132
20,21,0.200923,43,0,0.430046,12300.0,10,0,2,0,0.0,0,12300.000000,0,8,5289.569957,7010.430043,5289.569957
21,22,0.025656,38,0,0.475841,3000.0,7,0,1,0,2.0,1,1000.000000,0,6,1427.524158,1572.475842,475.841386
22,23,1.000000,39,0,0.241104,2500.0,4,0,0,0,0.0,0,2500.000000,0,4,602.758897,1897.241103,602.758897
23,24,0.075427,32,0,0.085512,7916.0,6,0,0,0,0.0,0,7916.000000,0,6,676.914488,7239.085512,676.914488
24,25,0.046560,58,0,0.241622,2416.0,9,0,1,0,0.0,0,2416.000000,0,8,583.758378,1832.241622,583.758378
25,26,0.392248,50,0,1.595253,4676.0,14,0,3,0,1.0,1,2338.000000,0,11,7459.404749,-2783.404749,3729.702374
26,27,0.052436,58,0,0.097672,8333.0,22,0,1,0,0.0,0,8333.000000,0,21,813.902326,7519.097674,813.902326
27,28,0.034421,69,0,0.042383,2500.0,17,0,0,0,1.0,0,1250.000000,0,17,105.957617,2394.042382,52.978809
28,29,0.452516,24,0,0.011761,3400.0,1,0,0,0,0.0,0,3400.000000,0,1,39.988240,3360.011760,39.988240
29,30,0.392995,58,2,0.436103,5500.0,15,0,1,0,0.0,0,5500.000000,2,14,2398.563899,3101.436101,2398.563899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149970,149971,0.025449,58,0,0.253855,15500.0,7,0,2,0,2.0,0,5166.666667,0,5,3934.746145,11565.253855,1311.582048
149971,149972,0.058001,83,0,0.013997,5000.0,6,0,0,0,0.0,0,5000.000000,0,6,69.986005,4930.013995,69.986005
149972,149973,0.071273,42,0,0.008638,6945.0,3,0,0,0,1.0,0,3472.500000,0,3,59.991361,6885.008639,29.995681
149973,149974,1.026395,44,0,0.494819,5500.0,7,0,1,0,1.0,0,2750.000000,0,6,2721.505182,2778.494818,1360.752591
149974,149975,0.962721,61,2,0.603479,5000.0,11,0,1,0,0.0,0,5000.000000,2,10,3017.396520,1982.603480,3017.396520
149975,149976,0.022088,58,0,2716.000000,0.0,8,0,2,0,0.0,0,0.000000,0,6,0.000000,0.000000,0.000000
149976,149977,0.000627,76,0,60.000000,0.0,5,0,0,0,0.0,0,0.000000,0,5,0.000000,0.000000,0.000000
149977,149978,0.236450,29,0,349.000000,0.0,3,0,0,0,0.0,0,0.000000,0,3,0.000000,0.000000,0.000000
149978,149979,0.917635,52,2,0.259496,2500.0,4,0,0,0,0.0,0,2500.000000,2,4,648.740505,1851.259495,648.740505
149979,149980,0.224711,55,0,0.057235,8700.0,7,0,0,0,0.0,1,8700.000000,0,7,497.942769,8202.057231,497.942769
149980,149981,0.067644,64,0,0.254976,5525.0,12,0,1,0,0.0,0,5525.000000,0,11,1408.745024,4116.254976,1408.745024
149981,149982,0.810012,43,0,0.121752,6849.0,4,0,0,0,4.0,0,1369.800000,0,4,833.878249,6015.121751,166.775650
149982,149983,0.021046,37,0,0.250272,2760.0,8,0,0,0,3.0,0,690.000000,0,8,690.749729,2069.250271,172.687432
149983,149984,0.002485,82,0,0.000800,5000.0,5,0,0,0,0.0,0,5000.000000,0,5,3.999200,4996.000800,3.999200
149984,149985,0.037548,84,0,25.000000,0.0,5,0,0,0,0.0,0,0.000000,0,5,0.000000,0.000000,0.000000
149985,149986,0.954409,26,0,0.324962,1950.0,4,0,0,0,0.0,0,1950.000000,0,4,633.675038,1316.324962,633.675038
149986,149987,0.168102,49,0,0.080384,5000.0,16,0,0,0,1.0,0,2500.000000,0,16,401.919615,4598.080385,200.959807
149987,149988,1.000000,28,0,0.055692,3249.0,3,1,0,0,0.0,0,3249.000000,1,3,180.944309,3068.055691,180.944309
149988,149989,0.902051,31,1,0.347924,7515.0,10,0,1,0,0.0,0,7515.000000,1,9,2614.652076,4900.347924,2614.652076
149989,149990,0.013356,62,0,0.001408,9233.0,4,0,0,0,3.0,0,2308.250000,0,4,12.998596,9220.001404,3.249649
149990,149991,0.055518,46,0,0.609779,4335.0,7,0,1,0,2.0,0,1445.000000,0,6,2643.390222,1691.609778,881.130074
149991,149992,0.104112,59,0,0.477658,10316.0,10,0,2,0,0.0,0,10316.000000,0,8,4927.522342,5388.477658,4927.522342
149992,149993,0.871976,50,0,4132.000000,0.0,11,0,1,0,3.0,0,0.000000,0,10,0.000000,0.000000,0.000000
149993,149994,1.000000,22,0,0.000000,820.0,1,0,0,0,0.0,0,820.000000,0,1,0.000000,820.000000,0.000000
149994,149995,0.385742,50,0,0.404293,3400.0,7,0,0,0,0.0,0,3400.000000,0,7,1374.595707,2025.404293,1374.595707
149995,149996,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0,0,2100.000000,0,3,472.774869,1627.225131,472.774869
149996,149997,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0,0,1861.333333,0,3,4001.283436,1582.716564,1333.761145
149997,149998,0.246044,58,0,3870.000000,0.0,18,0,1,0,0.0,0,0.000000,0,17,0.000000,0.000000,0.000000
149998,149999,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0,0,5716.000000,0,4,0.000000,5716.000000,0.000000
149999,150000,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0,0,8158.000000,0,6,2038.750092,6119.249908,2038.750092

In [5]:
df.to_csv("trainfull.csv")

*<center> Créer le dataset de training: trainfull </center>*

In [6]:
source = api.create_source('../handson-ml2/trainfull.csv')

In [7]:
origin_dataset = api.create_dataset(source)

## Troisième étape: Séparation en train et val

*<center>Split 80/20 du trainfull en train et validation</center>*

In [8]:
train_dataset = api.create_dataset (origin_dataset, {"name": "Train80", "sample_rate":0.8, "seed": "myseed"})

In [10]:
val_dataset = api.create_dataset (origin_dataset, {"name": "Val", "sample_rate":0.8, "seed": "myseed", "out_of_bag": True})

## Quatrième étape: Préparer les données de test

In [11]:
data = read_csv('../handson-ml2/kaggle-give-me-credit-test.csv')

In [12]:
data = data.rename(columns={"Unnamed: 0": "Id"})
data['IncomePerPerson'] = data['MonthlyIncome']/ (data['NumberOfDependents']+1)
data['NumberOfDaysLate'] = data['NumberOfTimes90DaysLate']+ data['NumberOfTime60-89DaysPastDueNotWorse']+ data['NumberOfTime30-59DaysPastDueNotWorse']
data['NumberCreditLines'] = data['NumberOfOpenCreditLinesAndLoans']- data['NumberRealEstateLoansOrLines']
data['MonthlyDebt'] = data['MonthlyIncome'] * data['DebtRatio']
data['MonthlyBalance'] = data['MonthlyIncome'] - data['MonthlyDebt']
data['DebtPerPerson'] = data['MonthlyDebt'] / ( data['NumberOfDependents'] + 1 )
data

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,IncomePerPerson,NumberOfDaysLate,NumberCreditLines,MonthlyDebt,MonthlyBalance,DebtPerPerson
0,1,NaN,0.885519,43,0,0.177513,5700.0,4,0,0,0,0.0,5700.000000,0,4,1011.822487,4688.177513,1011.822487
1,2,NaN,0.463295,57,0,0.527237,9141.0,15,0,4,0,2.0,3047.000000,0,11,4819.472759,4321.527241,1606.490920
2,3,NaN,0.043275,59,0,0.687648,5083.0,12,0,1,0,2.0,1694.333333,0,11,3495.312354,1587.687646,1165.104118
3,4,NaN,0.280308,38,1,0.925961,3200.0,7,0,2,0,0.0,3200.000000,1,5,2963.074038,236.925962,2963.074038
4,5,NaN,1.000000,27,0,0.019917,3865.0,4,0,0,0,1.0,1932.500000,0,4,76.980082,3788.019918,38.490041
5,6,NaN,0.509791,63,0,0.342429,4140.0,4,0,0,0,1.0,2070.000000,0,4,1417.657571,2722.342429,708.828786
6,7,NaN,0.587778,50,0,1048.000000,0.0,5,0,0,0,3.0,0.000000,0,5,0.000000,0.000000,0.000000
7,8,NaN,0.046149,79,1,0.369170,3301.0,8,0,1,0,1.0,1650.500000,1,7,1218.630830,2082.369170,609.315415
8,9,NaN,0.013527,68,0,2024.000000,NaN,4,0,1,0,0.0,NaN,0,3,NaN,NaN,NaN
9,10,NaN,1.000000,23,98,0.000000,0.0,0,98,0,98,0.0,0.000000,294,0,0.000000,0.000000,0.000000
10,11,NaN,0.028485,37,0,0.319687,7400.0,8,0,1,0,1.0,3700.000000,0,7,2365.680315,5034.319685,1182.840157
11,12,NaN,0.085077,52,0,0.903552,4250.0,6,0,2,0,0.0,4250.000000,0,4,3840.096446,409.903554,3840.096446
12,13,NaN,0.010596,68,0,0.007782,3854.0,16,0,0,0,0.0,3854.000000,0,16,29.992217,3824.007783,29.992217
13,14,NaN,0.380679,30,0,0.377449,2500.0,12,0,0,0,1.0,1250.000000,0,12,943.622550,1556.377450,471.811275
14,15,NaN,0.556894,56,0,0.697347,6822.0,14,0,1,0,1.0,3411.000000,0,13,4757.302653,2064.697347,2378.651326
15,16,NaN,0.079056,28,0,0.105831,7133.0,8,0,0,0,0.0,7133.000000,0,8,754.894171,6378.105829,754.894171
16,17,NaN,0.543013,72,0,0.461786,5900.0,10,0,2,0,1.0,2950.000000,0,8,2724.538214,3175.461786,1362.269107
17,18,NaN,0.112346,37,0,0.144326,2916.0,7,0,0,0,0.0,2916.000000,0,7,420.855675,2495.144325,420.855675
18,19,NaN,0.648285,29,0,0.174850,4500.0,4,0,0,1,1.0,2250.000000,1,4,786.825149,3713.174851,393.412574
19,20,NaN,0.686406,43,0,487.000000,NaN,10,0,0,0,1.0,NaN,0,10,NaN,NaN,NaN
20,21,NaN,0.085910,48,0,0.196156,8844.0,8,0,1,0,1.0,4422.000000,0,7,1734.803841,7109.196159,867.401920
21,22,NaN,0.158549,61,0,0.353158,11920.0,13,0,1,0,0.0,11920.000000,0,12,4209.646841,7710.353159,4209.646841
22,23,NaN,0.009303,69,0,0.384451,6083.0,4,0,2,0,0.0,6083.000000,0,2,2338.615549,3744.384451,2338.615549
23,24,NaN,0.957442,69,2,0.666338,3041.0,8,1,1,1,1.0,1520.500000,4,7,2026.333663,1014.666337,1013.166832
24,25,NaN,0.442489,50,1,0.286555,8500.0,17,0,1,0,2.0,2833.333333,1,16,2435.713446,6064.286555,811.904482
25,26,NaN,0.125267,51,0,3825.000000,NaN,10,0,2,0,0.0,NaN,0,8,NaN,NaN,NaN
26,27,NaN,1.000000,45,0,0.000000,4750.0,1,0,0,0,1.0,2375.000000,0,1,0.000000,4750.000000,0.000000
27,28,NaN,0.181481,67,0,1509.000000,NaN,12,0,1,0,0.0,NaN,0,11,NaN,NaN,NaN
28,29,NaN,0.729397,34,0,0.335555,7500.0,6,0,2,0,1.0,3750.000000,0,4,2516.664442,4983.335558,1258.332221
29,30,NaN,0.024445,47,0,5810.000000,NaN,20,0,2,0,2.0,NaN,0,18,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101473,101474,NaN,0.662634,73,0,0.277090,5333.0,10,0,0,0,0.0,5333.000000,0,10,1477.722911,3855.277089,1477.722911
101474,101475,NaN,1.032484,47,0,0.365243,2036.0,2,0,0,1,0.0,2036.000000,1,2,743.634756,1292.365244,743.634756
101475,101476,NaN,1.000000,35,0,0.240467,1284.0,1,0,0,0,2.0,428.000000,0,1,308.759533,975.240467,102.919844
101476,101477,NaN,0.015908,68,0,0.217593,8400.0,11,0,2,0,1.0,4200.000000,0,9,1827.782410,6572.217590,913.891205
101477,101478,NaN,0.096295,69,0,0.052316,3000.0,4,0,0,0,0.0,3000.000000,0,4,156.947685,2843.052315,156.947685
101478,101479,NaN,0.000000,43,0,0.095303,5833.0,6,0,1,0,2.0,1944.333333,0,5,555.904697,5277.095303,185.301566
101479,101480,NaN,0.024788,71,0,0.361319,3608.0,22,1,2,0,0.0,3608.000000,1,20,1303.638681,2304.361319,1303.638681
101480,101481,NaN,0.217134,48,0,0.602701,5257.0,15,0,1,0,0.0,5257.000000,0,14,3168.397301,2088.602699,3168.397301
101481,101482,NaN,0.048971,51,0,0.339154,7043.0,14,0,1,0,2.0,2347.666667,0,13,2388.660847,4654.339153,796.220282
101482,101483,NaN,1.000000,33,98,0.000000,2000.0,0,98,0,98,3.0,500.000000,294,0,0.000000,2000.000000,0.000000
101483,101484,NaN,0.124484,82,0,0.003797,7636.0,2,0,0,0,0.0,7636.000000,0,2,28.996206,7607.003794,28.996206
101484,101485,NaN,0.065636,60,0,0.306759,7500.0,10,0,3,0,1.0,3750.000000,0,7,2300.693242,5199.306758,1150.346621
101485,101486,NaN,0.043139,81,0,0.014548,3917.0,4,0,0,0,0.0,3917.000000,0,4,56.985452,3860.014548,56.985452
101486,101487,NaN,0.078280,55,0,0.495979,2983.0,16,0,2,0,1.0,1491.500000,0,14,1479.504021,1503.495979,739.752010
101487,101488,NaN,0.000961,64,0,2.000000,NaN,5,0,0,0,0.0,NaN,0,5,NaN,NaN,NaN
101488,101489,NaN,0.179587,68,0,0.268839,7550.0,8,0,1,0,0.0,7550.000000,0,7,2029.731158,5520.268842,2029.731158
101489,101490,NaN,1.031359,34,0,0.305339,3333.0,6,0,0,0,1.0,1666.500000,0,6,1017.694660,2315.305340,508.847330
101490,101491,NaN,0.875649,43,2,0.512893,9500.0,8,0,5,0,2.0,3166.666667,2,3,4872.487110,4627.512890,1624.162370
101491,101492,NaN,0.228665,44,1,0.080143,8958.0,6,0,0,0,0.0,8958.000000,1,6,717.919856,8240.080144,717.919856
101492,101493,NaN,0.139191,58,1,3.183267,501.0,11,0,1,0,3.0,125.250000,1,10,1594.816733,-1093.816733,398.704183
101493,101494,NaN,0.035549,58,0,0.290323,11128.0,7,0,2,0,2.0,3709.333333,0,5,3230.709681,7897.290319,1076.903227
101494,101495,NaN,0.218356,56,0,0.295803,1500.0,3,0,0,0,0.0,1500.000000,0,3,443.704197,1056.295803,443.704197
101495,101496,NaN,0.718874,35,1,0.308047,4125.0,8,0,0,1,2.0,1375.000000,2,8,1270.691953,2854.308047,423.563984
101496,101497,NaN,0.021654,78,0,18.000000,NaN,8,0,0,0,0.0,NaN,0,8,NaN,NaN,NaN
101497,101498,NaN,0.045230,67,0,0.012198,5000.0,4,0,0,0,0.0,5000.000000,0,4,60.987800,4939.012200,60.987800
101498,101499,NaN,0.282653,24,0,0.068522,1400.0,5,0,0,0,0.0,1400.000000,0,5,95.931478,1304.068522,95.931478
101499,101500,NaN,0.922156,36,3,0.934217,7615.0,8,0,2,0,4.0,1523.000000,3,6,7114.065783,500.934217,1422.813157
101500,101501,NaN,0.081596,70,0,836.000000,NaN,3,0,0,0,NaN,NaN,0,3,NaN,NaN,NaN
101501,101502,NaN,0.335457,56,0,3568.000000,NaN,8,0,2,1,3.0,NaN,1,6,NaN,NaN,NaN
101502,101503,NaN,0.441842,29,0,0.198918,5916.0,12,0,0,0,0.0,5916.000000,0,12,1176.801083,4739.198917,1176.801083

In [13]:
data.to_csv("test.csv")

*<center> Créer un dataset de test </center>*

In [14]:
test_source = api.create_source('../handson-ml2/test.csv')
api.ok(test_source)

True

In [15]:
test_dataset = api.create_dataset(test_source)